### ISSUE TITLE
Export the type Constraints

### ISSUE THREAD

**Issue by tleperou** [rahulrao0209/checkpass#1]
🙌 

Great job @rahulrao0209.

Is that OK to export the type Constraints too ?

Maybe I'm missing it 🤔

**Comment by rahulrao0209** [comment]
Hello @tleperou
Firstly, thanks for taking the time to try out the library!

As to your question, I believe you're saying we need to _export the Constraints type_ as well.
On those lines, I've made the updates so you could do something like this
![checkpass-api-usage](https://user-images.githubusercontent.com/63695122/236615124-f6409241-b155-4081-9f0a-f794fb89173d.png)

This should make it easier to consume the library code. You will find these updates in version 2.0.1 or version 1.0.6 (they're both actually the same and don't have any breaking changes.)

There is also version 3.0.0 which has a major API update. The code now checks against all the constraints simultaneously and returns an object with details about all the constraints. Something like this
![checkpass-v3-API-usage](https://user-images.githubusercontent.com/63695122/236615422-d9dfb237-4bc1-482e-b00f-ed743f41e8be.png)
So as you can see above, the constraints _minCapitalLetters_ and _minSpecialCharacters_ are failing and so they have value set to true and a corresponding generic failure message.

This is done to make the usage of the library more flexible as the user can decide what to do with the returned constrained checks as opposed to just getting a string based on one of the failed checks.
Please use versions **1.0.6 or 2.0.1** to use the code as you have been. Version 3 has an API update which would work differently as above.

**Comment by tleperou** [comment]
Awesome! Well, thanks for taking time to explain all of that.

Is the version 3 stable and ready to used?

🖖

**Comment by rahulrao0209** [comment]
Yes, it should be. Let me know if anything does not work right or if you face any issues.

**Comment by rahulrao0209** [comment]
Closing this issue as the Constraints type has been exposed.
